### ISSUE TITLE
detach() crashes if attach() or once() was not called first

### ISSUE THREAD

**Issue by beegee-tokyo** [bertmelis/Ticker-esp32#1]
void **`Ticker::detach()`** crashes if there was no call to **`Ticker::attach()`**, **`Ticker::attach_ms()`**, **`Ticker::attach()`** or **`Ticker::once_ms()`** before.
**_Solution;_**
Change
```
void Ticker::detach() {
  xTimerStop(_timerHandle, 0);
}
```
to
```
void Ticker::detach() {
  if (_timerHandle) {
    xTimerStop(_timerHandle, 0);
  }
}
```

**Comment by bertmelis** [comment]
Fixed in https://github.com/bertmelis/Ticker-esp32/commit/9e1794e6cdd66aa3b91aebb2c16a73b6332e5a02

Did add an extra check to see if the timer is active.

Thanks!
