### ISSUE TITLE
Better Alignment with ESP8266 Ticker

### ISSUE THREAD

**Issue by timpur** [bertmelis/Ticker-esp32#3]
Wondering why you didnt use the timer id for args ?

> An identifier that is assigned to the timer being created. Typically this would be used in the timer callback function to identify which timer expired when the same callback function is assigned to more than one timer, or together with the vTimerSetTimerID() and pvTimerGetTimerID() API functions to save a value between calls to the timer's callback function.

also is it possible to use a lambda expression to remove the need of the list? so it can be stateless.

_timerHandle = xTimerCreate("Ticker", pdMS_TO_TICKS(milliseconds), (repeat)?pdTRUE:pdFALSE, (void*)arg, [callback](TimerHandle_t xTimer){
 void* arg = pvTimerGetTimerID(xTimer );
 callback(arg);
});

it would be nice to not need the list of tickers?

**Comment by timpur** [comment]
dont think [capature] will work so maybe use xTaskGetApplicationTaskTag to set the callback ?
`TaskHookFunction_t xTaskGetApplicationTaskTag( TaskHandle_t xTask );`
`typedef BaseType_t (*TaskHookFunction_t)( void * );`

I might fork and try out later. Wondering on your thoughts?

**Comment by bertmelis** [comment]
I don't have much to say actually. My knowledge of FreeRTOS is very limited and I only made this library as an interface like the ESP8266. I didn't think about efficiency nor in terms of speed nor in memory usage. If someone makes a better alternative I'll propably switch over.

That said, I did wanted to get rid of the Ticker-vector but you have to link the callback and optional argument somehow to the `TimerHandle_t`. So you'll have to store that link somewhere. You could assign the position of the Ticker* as TimerID so you don't have to loop each time the timer fires.
But if you know of an alternative way, I'm happy to look into it or link this repo to your better one.

**Comment by timpur** [comment]
All g if I have time I might look into it also 
Would be nice but not the end of the world :P

**Comment by bertmelis** [comment]
For the time being, I'm going to keep the current design and wait for the ESP-IDF to upgrade to 3.x which implements a timer api.

**Comment by timpur** [comment]
Yep sounds good :)

**Comment by bertmelis** [comment]
Meanwhile esp32 core has been updated so FreeRTOS software timers can be replaced by SDK-timers: see https://github.com/espressif/arduino-esp32/blob/master/tools/sdk/include/esp32/esp_timer.h

I'm already working on it.

A further improvement is to include the use of functional so you can _std::bind_ callbacks. I saw that this will also be implemented for the esp8266 core.

**Comment by timpur** [comment]
Awsome :)

**Comment by bertmelis** [comment]
Will be maintained in esp32 core.
